services:
  auth-postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: tam_an
      POSTGRES_PASSWORD: tam_an_password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  users-postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: tam_an
      POSTGRES_PASSWORD: tam_an_password
      POSTGRES_DB: users_db
    ports:
      - "5434:5432"
    volumes:
      - users_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata:
  users_pgdata:
